// Language keywords to filter out (combined across JS/TS, Rust, Python, Go).
// Shared by Cmd+click symbol navigation and the hover affordance so the
// clickable underline appears on exactly the tokens that actually navigate.
const KEYWORDS = new Set([
  // JS/TS
  "if",
  "else",
  "for",
  "while",
  "do",
  "switch",
  "case",
  "break",
  "continue",
  "return",
  "throw",
  "try",
  "catch",
  "finally",
  "new",
  "delete",
  "typeof",
  "instanceof",
  "void",
  "in",
  "of",
  "let",
  "const",
  "var",
  "function",
  "class",
  "extends",
  "super",
  "this",
  "import",
  "export",
  "from",
  "default",
  "as",
  "async",
  "await",
  "yield",
  "true",
  "false",
  "null",
  "undefined",
  "with",
  "debugger",
  "enum",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  "static",
  "type",
  // Rust
  "fn",
  "mut",
  "ref",
  "pub",
  "use",
  "mod",
  "crate",
  "self",
  "Self",
  "struct",
  "trait",
  "impl",
  "where",
  "match",
  "loop",
  "move",
  "unsafe",
  "extern",
  "dyn",
  "macro",
  // Python
  "def",
  "and",
  "or",
  "not",
  "is",
  "lambda",
  "pass",
  "raise",
  "global",
  "nonlocal",
  "assert",
  "elif",
  "except",
  "None",
  "True",
  "False",
  // Go
  "func",
  "map",
  "chan",
  "go",
  "defer",
  "select",
  "range",
  "fallthrough",
  "goto",
]);

/**
 * Whether a token's text is an identifier worth resolving a definition for.
 * Filters out punctuation, keywords, and tokens too short to be meaningful.
 */
export function isNavigableIdentifier(text: string): boolean {
  if (!text) return false;
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(text)) return false;
  if (text.length < 3) return false;
  if (KEYWORDS.has(text)) return false;
  return true;
}
