/**
 * Preferences utilities
 */

// Re-export font constants from preferencesSlice
export {
  CODE_FONT_SIZE_DEFAULT,
  CODE_FONT_SIZE_MIN,
  CODE_FONT_SIZE_MAX,
  CODE_FONT_SIZE_STEP,
  CODE_FONT_FAMILY_DEFAULT,
  TERMINAL_FONT_FAMILY_DEFAULT,
  TERMINAL_FONT_SIZE_DEFAULT,
  TERMINAL_FONT_SIZE_MIN,
  TERMINAL_FONT_SIZE_MAX,
  TERMINAL_FONT_SIZE_STEP,
  TERMINAL_FONT_WEIGHT_DEFAULT,
  TERMINAL_LINE_HEIGHT_DEFAULT,
  TERMINAL_LINE_HEIGHT_MIN,
  TERMINAL_LINE_HEIGHT_MAX,
  TERMINAL_LINE_HEIGHT_STEP,
  TERMINAL_LETTER_SPACING_DEFAULT,
  TERMINAL_LETTER_SPACING_MIN,
  TERMINAL_LETTER_SPACING_MAX,
  TERMINAL_LETTER_SPACING_STEP,
} from "../stores/slices/preferencesSlice";

export interface RecentRepo {
  path: string;
  name: string; // directory name for display
  lastOpened: string; // ISO date
}
